language: go
go:
- 1.8.3
- master
matrix:
  allow_failures:
  - go: master
branches:
  only:
  - develop
  - master
install:
  - go get github.com/naoina/toml
  - go get github.com/stretchr/testify/assert
  - go get github.com/jarcoal/httpmock
script:
  - go build -v ./...
  - go test -v ./...
