language: go
go:
- 1.9.1
- master
matrix:
  allow_failures:
  - go: master
branches:
  only:
  - develop
  - master
install:
  - go get github.com/BurntSushi/toml
  - go get github.com/stretchr/testify/assert
  - go get github.com/jarcoal/httpmock
  - go get github.com/maxim2266/csvplus
script:
  - make
  - make test
