language: go
go:
- 1.9.1
- master
matrix:
  allow_failures:
  - go: master
branches:
  only:
  - develop
  - master
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libgpgme11 libassuan-dev libassuan0 libgpg-error0 gnupg2
install:
  - go get github.com/BurntSushi/toml
  - go get github.com/stretchr/testify/assert
  - go get github.com/jarcoal/httpmock
  - go get github.com/maxim2266/csvplus
  - go get github.com/proglottis/gpgme
script:
  - make
  - make test
