dist: trusty
language: go
go:
- "1.10.1"
- master
matrix:
  allow_failures:
  - go: master
branches:
  only:
  - develop
  - master
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libgpgme11 libgpgme11-dev libassuan-dev libassuan0 libgpg-error0 gnupg2
install:
  - go get github.com/BurntSushi/toml
  - go get github.com/stretchr/testify/assert
  - go get github.com/jarcoal/httpmock
  - go get github.com/maxim2266/csvplus
  - go get github.com/proglottis/gpgme
  - go get github.com/keltia/proxy
script:
  - make
  - make test
